import { GatewayLink, SkillItem, TimelineItem, ArchitectureProject } from './types';

export const PERSONAL_INFO = {
  name: 'Habibur Rohman Hayat',
  callsign: 'HAYAT.INFRA',
  role: 'Tech Architect & System Engineer',
  tagline: '"Every Expert Was Once a Beginner."',
  subheading: 'Architecting AI Automation, Full Stack Logic, and Robust SysAdmin Infrastructures.',
  bio: 'Enthusiastic student and self-taught tech enthusiast from Bangladesh. Mastering modern technology, AI orchestration, and digital infrastructure through relentless research and hands-on laboratory deployments.',
  philosophy: 'I use music to fuel my creative workflows and maintain high-performance energy during long development sessions. Obsessed with clean modular code, self-hosted servers, and deterministic systems.',
  location: 'Sarishabari, Jamalpur, Bangladesh',
  coordinates: '24.7438° N, 89.8315° E',
  status: 'ACTIVE_SESSION // DEV_MODE',
  eiin: '110216',
  email: 'hrhayat2008@gmail.com',
  photoUrl: 'https://scontent.fdac11-1.fna.fbcdn.net/v/t39.30808-6/650765482_122277187742218950_8349335722733324315_n.jpg?stp=dst-jpg_tt6&cstp=mx1365x1838&ctp=s1365x1838&_nc_cat=104&ccb=1-7&_nc_sid=833d8c&_nc_eui2=AeHU3zbQCuoooELk8_pfYB9EJsHk4yrjyr4mweTjKuPKvq1EPJjTXh8jU31raxzkURQ_PMbS0GMlcJQ_pzKJ0P6G&_nc_ohc=tQt_TI-u5h8Q7kNvwEsqwcG&_nc_oc=AdoOMUe-cwLjN6QN0tsABUs-cbmNIPms8yv4tPf-yWlyiMQXF33AmOq11f9mNHtlVlk&_nc_zt=23&_nc_ht=scontent.fdac11-1.fna&_nc_gid=ewhdilBdhd33PEQh7AB6Lw&_nc_ss=7b2a8&oh=00_AQLFozFR9TNA1UHHsdk2_fh9S1x8QVRpBEVWm0lcLUv4hg&oe=6AAF5A20',
  ambientGif: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhhPOjpKse2iEtLAz8lpmjwk5W_oPaNhSbzjlzv-9d68QQ6A70iJHB6DVB18ujDf552T9VMFALBrxxxQWtvoi60vVHLuYhWH-g6vcNs06wUlRF-FhS1E2Ru4G0SpOQDybEnsxZyp14114w2oLMEozW0V_IFdEdsBkG6u00DwmdyK0mED7U7gm7hvo6BJwA/w320-h180/crealify.gif',
};

export const GATEWAYS: GatewayLink[] = [
  {
    id: 'github',
    name: 'GitHub',
    label: 'GITHUB',
    handle: '@hayat-dev',
    url: 'https://github.com',
    icon: 'github',
    color: '#00f5ff',
    type: 'code',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    label: 'FACEBOOK',
    handle: 'Habibur Rohman Hayat',
    url: 'https://facebook.com',
    icon: 'facebook',
    color: '#1877f2',
    type: 'social',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    label: 'INSTAGRAM',
    handle: '@hayat.infra',
    url: 'https://instagram.com',
    icon: 'instagram',
    color: '#e4405f',
    type: 'social',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    label: 'WHATSAPP',
    handle: 'Direct Protocol',
    url: 'https://wa.me/?text=Hello%20Habibur%20Rohman%20Hayat',
    icon: 'message-circle',
    color: '#25d366',
    type: 'comm',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    label: 'TELEGRAM',
    handle: '@HayatArch',
    url: 'https://t.me',
    icon: 'send',
    color: '#0088cc',
    type: 'comm',
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    label: 'X_TWITTER',
    handle: '@HayatArch',
    url: 'https://x.com',
    icon: 'twitter',
    color: '#ffffff',
    type: 'social',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    label: 'YOUTUBE',
    handle: 'Tech Streams',
    url: 'https://youtube.com',
    icon: 'youtube',
    color: '#ff0000',
    type: 'social',
  },
  {
    id: 'email',
    name: 'Email Protocol',
    label: 'EMAIL',
    handle: 'hrhayat2008@gmail.com',
    url: 'mailto:hrhayat2008@gmail.com',
    icon: 'mail',
    color: '#00f5ff',
    type: 'contact',
  },
];

export const SKILL_MATRIX: SkillItem[] = [
  // Development
  {
    id: 'python',
    name: 'Python 3.x',
    category: 'dev',
    level: 92,
    tags: ['Scripting', 'Automation', 'AsyncIO', 'Data Processing'],
    description: 'Core programming language for backend engines, AI pipelines, and operational automation scripts.',
  },
  {
    id: 'fastapi',
    name: 'FastAPI & REST',
    category: 'dev',
    level: 88,
    tags: ['Microservices', 'Pydantic', 'Swagger Docs', 'JWT'],
    description: 'Constructing robust, asynchronous APIs with type safety, real-time endpoints, and validation.',
  },
  {
    id: 'js-ts',
    name: 'JavaScript & TypeScript',
    category: 'dev',
    level: 86,
    tags: ['ESNext', 'Static Typing', 'DOM Engine', 'Node.js'],
    description: 'Modern full-stack client and server development with type-safe patterns and modular bundles.',
  },
  {
    id: 'web-stack',
    name: 'Full Stack Web Architecture',
    category: 'dev',
    level: 85,
    tags: ['React', 'Tailwind CSS', 'Vite', 'State Management'],
    description: 'End-to-end web apps with responsive mobile-first layouts, accessible designs, and high FPS rendering.',
  },
  // SysAdmin
  {
    id: 'linux',
    name: 'Linux OS & Shell',
    category: 'sysadmin',
    level: 94,
    tags: ['Debian', 'Ubuntu', 'Arch', 'Bash / Zsh Scripting', 'Systemd'],
    description: 'Kernel management, permissions, daemon supervision, automated backups, and headless CLI mastery.',
  },
  {
    id: 'networking',
    name: 'Networking & Security',
    category: 'sysadmin',
    level: 84,
    tags: ['TCP/IP', 'DNS / Reverse Proxy', 'SSH Tunneling', 'UFW / Iptables', 'Cloudflare'],
    description: 'Secure perimeter configuration, port forwarding, Nginx/Caddy proxies, SSL/TLS certifications, and mesh VPNs.',
  },
  {
    id: 'ai-auto',
    name: 'AI Automation & Agents',
    category: 'sysadmin',
    level: 90,
    tags: ['LLM Orchestration', 'n8n Workflows', 'Webhooks', 'RAG Logic'],
    description: 'Autonomous agents, automated incident parsing, intelligent content routing, and workflow synthesis.',
  },
  {
    id: 'homelab',
    name: 'HomeLab Infrastructure',
    category: 'sysadmin',
    level: 88,
    tags: ['Docker Containers', 'Proxmox VE', 'Self-Hosted Apps', 'NAS Storage'],
    description: 'Private 24/7 server cluster operating internal services, media pipelines, git runners, and telemetry.',
  },
  // Interface
  {
    id: 'html-css',
    name: 'Modern CSS & Tailwind',
    category: 'interface',
    level: 92,
    tags: ['Flexbox & Grid', 'Responsive Tokens', 'Keyframe FX', 'Cyberpunk Bento'],
    description: 'Pixel-perfect, high-contrast user interfaces with smooth transitions, dark-mode ergonomics, and zero layout shift.',
  },
  {
    id: 'windows-prog',
    name: 'Windows Programming & Tools',
    category: 'interface',
    level: 82,
    tags: ['PowerShell Automation', 'Registry Tweaks', 'WSL2 Integration', 'Desktop Utilities'],
    description: 'Power-user system customization, environment bootstrapping, and bridge workflows between Windows and Linux.',
  },
  {
    id: 'ui-ux',
    name: 'UI / UX System Logic',
    category: 'interface',
    level: 85,
    tags: ['Information Architecture', 'Ergonomics', 'Micro-interactions', 'Telemetry UI'],
    description: 'Designing intuitive flows where technical complexity is abstracted into clean, actionable dashboards.',
  },
];

export const TIMELINE: TimelineItem[] = [
  {
    id: 'college',
    institution: 'Sarishabari Govt. College',
    degree: 'Higher Secondary Certificate (HSC) - Science',
    period: '2025 — 2027 // ONGOING',
    status: 'ongoing',
    location: 'Sarishabari, Jamalpur, Bangladesh',
    eiin: '110216',
    highlights: [
      'Focusing on Mathematics, Physics, and Information & Communication Technology (ICT)',
      'Directing independent laboratory research in system architecture and AI logic',
      'Active developer session mode with anticipated graduation in 2027',
    ],
  },
  {
    id: 'school',
    institution: 'Sarishabari R.D.M Model High School',
    degree: 'Secondary School Certificate (SSC) - Science',
    period: 'Completed 2025',
    status: 'completed',
    location: 'Sarishabari, Jamalpur, Bangladesh',
    highlights: [
      'Successfully completed high school curriculum with distinction in Science and Computer Fundamentals',
      'Built early foundational computing, script execution, and hardware troubleshooting skills',
      'Active participant in regional science, technology, and Olympiad initiatives',
    ],
  },
];

export const FEATURED_PROJECTS: ArchitectureProject[] = [
  {
    id: 'proj-1',
    title: 'Autonomous AI Orchestrator',
    codename: 'NEXUS-PIPELINE',
    category: 'AI & Automation',
    description: 'Event-driven automation engine connecting multi-modal LLM triggers to system bash scripts, automated telegram alerts, and cloud sync.',
    techStack: ['Python', 'FastAPI', 'Webhooks', 'Docker', 'Gemini API'],
    status: 'Active',
    metrics: { label: 'Efficiency Boost', value: '4.2x Faster' },
  },
  {
    id: 'proj-2',
    title: 'Linux HomeLab Cluster & Proxy',
    codename: 'HAYAT-VAULT',
    category: 'SysAdmin & Network',
    description: 'Self-hosted bare-metal node running containerized services with hardened SSL reverse-proxy, automatic failover, and zero-trust Cloudflare tunnels.',
    techStack: ['Linux Debian', 'Docker Compose', 'Nginx', 'UFW', 'WireGuard'],
    status: 'Deployed',
    metrics: { label: 'Uptime Reliability', value: '99.98%' },
  },
  {
    id: 'proj-3',
    title: 'FastAPI Microservice Gateway',
    codename: 'CORE-RELAY',
    category: 'Development',
    description: 'High-throughput async REST service serving token verification, real-time rate limiting, and system diagnostic telemetry.',
    techStack: ['Python 3.12', 'FastAPI', 'Pydantic v2', 'AsyncIO', 'JSON-RPC'],
    status: 'Lab Testing',
    metrics: { label: 'Response Latency', value: '< 18ms' },
  },
  {
    id: 'proj-4',
    title: 'Cyberpunk Bento System UI',
    codename: 'TERMINAL-OS',
    category: 'Interface & Frontend',
    description: 'High-contrast responsive developer portfolio and operational HUD inspired by cyber-architectural grids with smooth CSS spring transitions.',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Motion'],
    status: 'Active',
    metrics: { label: 'Frame Rate', value: '60 FPS Solid' },
  },
];
